fix: prisma schema
Keyneez/Keyneez-Server-Release pull request #4
Opened 2023-05-14 07:49 UTC by Tjdnjs

### 관련 이슈가 있다면 적어주세요.

db schema 재설계

## 📌 개발 이유

기능이 변화함에 따라 데이터베이스를 재설계 해야할 필요성을 느낌

## 💻 수정 사항

1. 필요 없는 테이블 삭제 (Character, Item, ...etc)
2. 필요 없는 column 삭제
3. 필요한 column 추가, 리스트 데이터타입 사용

## 🧪 테스트 방법

## ⛳️ 고민한 점 || 궁굼한 점

## 🎯 리뷰 포인트

## 📁 레퍼런스

2023-05-15 12:25 UTC, InHyeok-J reviewed
저희가 pk를 tablename_key로 이름을 짓는 이유가 있을까요?
데이터베이스의 key 종류가 많아서.. primary key의 네이밍으로 _key는 부족해보여서요!
id(식별자)의 네이밍은 어떤가요?

2023-05-15 12:46 UTC, InHyeok-J requested changes

2023-05-15 12:46 UTC, InHyeok-J commented on prisma/schema.prisma
>  model ContentMapping {
github review 창이 버그인지 코드가 이상해서 여기에 답니다!
  category        Int
  content         Int
  ContentMapping은 다대다 의 중간 테이블인데 pk만 유니크한 제약조건을 갖고 있어요 
  하나의 컨텐츠가 같은 카테고리랑 같이 mapping이 되면 안될거같아서 둘을 묶어서 유니크 제약조건이 달려야할거같아요

2023-05-15 12:46 UTC, InHyeok-J commented on prisma/schema.prisma
>  model Liked {
Liked, User(명사 단수), Contents(복수형) 이렇게 테이블 이름이 있는데 테이블 네이밍을 통일 시키면 좋을거같아요!
저희 컨벤션에는 파스칼케이스로만 하기로 했는데 명사+복수형으로 하면 좋을것 같아요(의견 있으면 답변해주시면 감사하겠습니다.)

2023-05-15 12:46 UTC, InHyeok-J commented on prisma/schema.prisma
>  model User {
저희가 User랑 Content에 데이터 생성 시간이랑 수정시간이 없는데 혹시 필요할 수도 있지 않을까.. 조심스럽게 건의해봅니다..!

2023-05-15 12:46 UTC, InHyeok-J commented on prisma/schema.prisma
> +  category_search String           @unique @db.VarChar(30)
저희 피그마 기준으로 카테고리/성향태그 이렇게 나뉘어져있는데 search는 tag의 네이밍은 어떨까요?

2023-05-15 12:46 UTC, InHyeok-J commented on prisma/schema.prisma
>    user      Int
여기뿐만 아니라 관계 맵핑돼있는 부분 모두 얘기하고 싶은데 Int 타입은 pk를 셋팅하는 곳인데 key의 이름이 그냥 테이블이름을 명시하고 있어서 해당 값이 다른 테이블의 pk를 나타내는지 헷갈릴것 같아요! 테이블의 pk 이름으로 수정하는건 어떨까요?

2023-05-15 12:46 UTC, InHyeok-J commented on prisma/schema.prisma
> +  user_phone   String   @unique @db.VarChar(30)
저희가 Oauth로 해당 데이터를 얻을 수 있나요?? age, gender, phone의 정보를 얻을 수 있는지 궁금합니다(디자인에는 없어서요!)

또한 피그마에는 닉네임으로 정의돼있는데 저희는 name을 받네요! Oauth에서 name을 받는다고 하면.. 1.nickname을 따로 추가할 건지 아니면 2.name에 닉네임을 넣을건지 궁금하네요!
만약 2번이라면 nickname으로 정의하는게 좋아보입니다!

2023-05-15 12:46 UTC, InHyeok-J commented on prisma/schema.prisma
> +  user_phone   String   @unique @db.VarChar(30)
밑에 생일도 데이터를 얻을 수 있는지 궁금해요!

2023-05-15 12:54 UTC, InHyeok-J commented on prisma/schema.prisma
> +  category_search String           @unique @db.VarChar(30)
또 저희가 생각해보니 하나의 content에 category가 정해져있다면 contents에 카테고리를 속성으로 두고, tag로만 다대다 해도 좋을것 같네요!!

2023-05-15 13:04 UTC, Tjdnjs commented on prisma/schema.prisma
>  model ContentMapping {
하나의 컨텐츠가 같은 카테고리랑 매핑된다는 게 무슨 말씀이시죠 ?

2023-05-15 13:08 UTC, Tjdnjs commented on prisma/schema.prisma
>  model Liked {
넵 모두 복수형으로 수정 하겠습니다!

2023-05-15 13:08 UTC, Tjdnjs commented on prisma/schema.prisma
> +  category_search String           @unique @db.VarChar(30)
> 저희 피그마 기준으로 카테고리/성향태그 이렇게 나뉘어져있는데 search는 tag의 네이밍은 어떨까요?

네이밍 바꾸는 것 좋은 생각인 것 같네요 !!

2023-05-15 13:09 UTC, Tjdnjs commented on prisma/schema.prisma
> +  category_search String           @unique @db.VarChar(30)
> 또 저희가 생각해보니 하나의 content에 category가 정해져있다면 contents에 카테고리를 속성으로 두고, tag로만 다대다 해도 좋을것 같네요!!

하나의 contents에 하나의 category가 달릴 지 아닐 지는 확실하지 않아서 이 부분은 기획분들과 이야기 나눠보아야할 것 같아요

2023-05-15 13:10 UTC, Tjdnjs commented on prisma/schema.prisma
> +  user_phone   String   @unique @db.VarChar(30)
> 저희가 Oauth로 해당 데이터를 얻을 수 있나요?? age, gender, phone의 정보를 얻을 수 있는지 궁금합니다(디자인에는 없어서요!)
> 
> 또한 피그마에는 닉네임으로 정의돼있는데 저희는 name을 받네요! Oauth에서 name을 받는다고 하면.. 1.nickname을 따로 추가할 건지 아니면 2.name에 닉네임을 넣을건지 궁금하네요! 만약 2번이라면 nickname으로 정의하는게 좋아보입니다!

말씀하신 데이터 다 받아올 수 있습니다 다만 어떤 데이터를 저희가 사용하게 될 지는 클라이언트 분들과 상의해보아야할 내용 같네요

2023-05-15 13:36 UTC, InHyeok-J commented on prisma/schema.prisma
>  model ContentMapping {
content pk 1 < -- > category 1  ==> 1,1이 하나의 쌍으로 맵핑 되는데
content 1이가 category 1를 가질떄 다음에 또 같은 값을 가지면 중복되니깐 1,1쌍이 유니크여야 하지 않을까요?

2023-05-16 00:31 UTC, InHyeok-J commented on prisma/schema.prisma
>  model ContentMapping {
> 하나의 컨텐츠가 같은 카테고리랑 같이 mapping이 되면 안될거같아서 둘을 묶어서 유니크 제약조건이 달려야할거같아요

제가 어제 말을 이상하게 했네요 ㅋㅋ 죄송합니다.. 다대다 테이블에서 Like 예시로 들면 유저 1이 컨텐츠 1을 좋아요 하고 
다시 중복 좋아요를 하면 안되니깐 유니크 제약사항이 추가되어야 한다는 얘기였습니다!

2023-05-16 00:37 UTC, InHyeok-J commented on prisma/schema.prisma
> +  category_search String           @unique @db.VarChar(30)
@Tjdnjs  기획 분과 얘기해보고 fix 하죠 ! 
그리고 저희가 현재 테이블 상으로 카테고리와 태그가 둘다 unique 제약 조건이 있어요. 근데 현재 테이블 구조 상으로 
pk 1번 : 활동(카테고리) - 동아리/서포터즈(태그)
pk 2번 : 활동(카테고리) ->캠페인/공모전(태그) ---> 카테고리에서 유니크 제약사항으로 Error 발생 할것 같아요!

저희 도메인 상에서 카테고리와 태그가 분리되니깐 카테고리(ContentCategory) 테이블/ 태그(ContentTag) 테이블을 분리하는것은 어떨까요?

사실 카테고리는 현재 도메인 상에 3개밖에 없어서 고민이 되지만.. 일단 태그와 카테고리 테이블이 분리가 되면 카테고리 기반 검색 쿼리가 훨씬 편해질것 같아요
현재 구조는 ContentCategory에 category가 활동인 모든 id와 맵핑된 content를 조회해야 할 것 같은데
카테고리가 분리되면 그냥 카테고리 id=1(예시) 인 content를 조회하면 쉽게 될것 같네요!

2023-05-16 00:40 UTC, InHyeok-J commented on prisma/schema.prisma
> +  user_phone   String   @unique @db.VarChar(30)
다 받아올 수 있으면 기획자 분들이랑 논의를 좀 해봐야할것 같네요. 사실 피그마 기준으로는 사용하지 않는 데이터들이지만 나중에 기획적으로 활용될 수 있는 가능성이 있다고 하면 두고 없으면 삭제해도 괜찮아보입니다

2023-05-16 03:14 UTC, Tjdnjs commented on prisma/schema.prisma
> +  category_search String           @unique @db.VarChar(30)
> @Tjdnjs 기획 분과 얘기해보고 fix 하죠 ! 그리고 저희가 현재 테이블 상으로 카테고리와 태그가 둘다 unique 제약 조건이 있어요. 근데 현재 테이블 구조 상으로 pk 1번 : 활동(카테고리) - 동아리/서포터즈(태그) pk 2번 : 활동(카테고리) ->캠페인/공모전(태그) ---> 카테고리에서 유니크 제약사항으로 Error 발생 할것 같아요!
> 
> 저희 도메인 상에서 카테고리와 태그가 분리되니깐 카테고리(ContentCategory) 테이블/ 태그(ContentTag) 테이블을 분리하는것은 어떨까요?
> 
> 사실 카테고리는 현재 도메인 상에 3개밖에 없어서 고민이 되지만.. 일단 태그와 카테고리 테이블이 분리가 되면 카테고리 기반 검색 쿼리가 훨씬 편해질것 같아요 현재 구조는 ContentCategory에 category가 활동인 모든 id와 맵핑된 content를 조회해야 할 것 같은데 카테고리가 분리되면 그냥 카테고리 id=1(예시) 인 content를 조회하면 쉽게 될것 같네요!

제가 테이블을 설계한 의도는 현재 필터링 할 때 들어오는 필터의 네이밍과 실제 카테고리의 네이밍이 달라서 그 부분을 테이블로 정의한 거였어요 ! (세 가지 카테고리를 글자수에 맞추어 이름 변경 해둔 것 같다고 말씀드린 부분 ! )

2023-05-16 04:42 UTC, InHyeok-J commented on prisma/schema.prisma
> +  category_search String           @unique @db.VarChar(30)
좋습니다! 이번주 회의때 완전 픽스하면 되겠네요!!

2023-05-18 12:23 UTC, InHyeok-J commented on prisma/schema.prisma
저희가 Tag랑 Category가 1:N인데 궁금한건 컨텐츠에 카테고리 1개, 태그 2개 맵핑 이런 경우가 없을까요..? 만약 있으면 조금 애매할 것 같은데 기획팀에게 한번 물어봐야할것 같네요.

2023-05-18 12:23 UTC, InHyeok-J commented on prisma/schema.prisma
> +  User     Users    @relation(fields: [user], references: [user_pk], onDelete: Cascade, map: "user_fk")
저번에 말한 user랑 User 이 차이는 어떻게 되나요?

2023-05-18 12:33 UTC, Tjdnjs commented on prisma/schema.prisma
> 저희가 Tag랑 Category가 1:N인데 궁금한건 컨텐츠에 카테고리 1개, 태그 2개 맵핑 이런 경우가 없을까요..? 만약 있으면 조금 애매할 것 같은데 기획팀에게 한번 물어봐야할것 같네요.

카테고리 한 개에 태그 2개씩 매핑으로 고정입니다

2023-05-18 12:37 UTC, Tjdnjs commented on prisma/schema.prisma
> +  User     Users    @relation(fields: [user], references: [user_pk], onDelete: Cascade, map: "user_fk")
클라이언트 전달 부분에 있어서 join 될 때 불려오는 이름은 테이블명으로 고정하고 매핑만 fk로 하기로 한 것 아니었나요 ?

2023-05-18 12:42 UTC, InHyeok-J commented on prisma/schema.prisma
아하 진짜 피그마에 있는 그대로 매핑되는군요 ! 알겠습니다

2023-05-30 15:37 UTC, merged